### ISSUE TITLE
Missing error paths in `write`

### ISSUE THREAD

**Issue by pqwy** [mirage/mirage-tcpip#105]
TCP, being a `FLOW`, has a write function whose [type](https://github.com/mirage/mirage/blob/master/types/V1.mli#L156) allows for signalling of errors.

But the actual [implementation](https://github.com/mirage/mirage-tcpip/blob/master/tcp/flow.ml#L54) of `write` doesn't seem to attempt to do so.

Therefore, when a unikernel connects via TCP and starts writing, if the other end closes the connection, the `write` hangs indefinitely somewhere below [`Pcb.write_wait_for`](https://github.com/mirage/mirage-tcpip/blob/master/tcp/pcb.ml#L501), even after the lower level decides to [give up](https://github.com/mirage/mirage-tcpip/blob/master/tcp/segment.ml#L260).

I also hit upon a memory leak with a unikernel that just keeps sending logs over TCP, but so far I failed to come up with a minimal case that reproduces this. I believe it's the hung writes keeping the buffer they've been given alive.

**Comment by talex5** [comment]
If you're not sure what's causing it, I'd suggest:
- Modify the lowel level code to give up sooner (e.g. 1st time on 3rd packets).
- Run with [tracing](http://openmirage.org/wiki/profiling) on and compare what happens to the good vs bad threads.

**Comment by samoht** [comment]
This should be fixed by #150 and #148
