### ISSUE TITLE
stackv4.create_connection hangs

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-tcpip#110]
I can't seem to use stackv4.create_connection with Xen to create connections when the interface was configured with a static IP.  When I attempt to do so, the unikernel claims to be sending an ARP probe for either the host (if it's local) or the default gateway (if the connection has been requested to a non-local address), but no such ARP request shows up on the bridge.  Since nobody sees the ARP probe, it's never answered, and unikernel hangs indefinitely waiting for a response.  I've been able to reproduce this on x86 and ARM.

If the interface is set up with DHCP, the client successfully sends an ARP probe and receives a reply, and successfully sends a SYN packet to initiate the connection.

https://gist.github.com/yomimono/e2a8e2988284a0362179 for code which fails; change config.ml to DHCP to see it succeed.

**Comment by talex5** [comment]
(I assume this is with the current `tcpip`, not with your ARP patches)

Does it work if you put a brief `sleep` at the start? Sometimes, Mirage is a bit too quick for Linux dom0.

Failing that... a trace from mirage-profile would be nice ;-)

**Comment by yomimono** [comment]
On 02/23/2015 06:30 PM, Thomas Leonard wrote:
>
> (I assume this is with the current |tcpip|, not with your ARP patches)
>
correct :)
>
> Does it work if you put a brief |sleep| at the start? Sometimes, 
> Mirage is a bit too quick for Linux dom0.
>
`OS.Time.sleep 1.0` indeed makes for a successful connection attempt.
>
> Failing that... a trace from mirage-profile would be nice ;-)
>
I agree that that would be helpful!  Unfortunately, it seems it reliably 
doesn't occur when tracing is enabled.

-Mindy

**Comment by talex5** [comment]
Anything on the Linux side (e.g. `dmesg`)?

**Comment by yomimono** [comment]
Here's `dmesg` from a `vif` attached to an affected run:

[302815.951167] device vif134.0 entered promiscuous mode
[302815.953719] IPv6: ADDRCONF(NETDEV_UP): vif134.0: link is not ready
[302816.022691] IPv6: ADDRCONF(NETDEV_CHANGE): vif134.0: link becomes ready
[302816.022792] xenbr0: port 4(vif134.0) entered forwarding state
[302816.022844] xenbr0: port 4(vif134.0) entered forwarding state
[302831.069431] xenbr0: port 4(vif134.0) entered forwarding state

Here's one from an unaffected run:

[304322.176315] device vif145.0 entered promiscuous mode
[304322.178690] IPv6: ADDRCONF(NETDEV_UP): vif145.0: link is not ready
[304322.244546] IPv6: ADDRCONF(NETDEV_CHANGE): vif145.0: link becomes ready
[304322.244590] xenbr0: port 4(vif145.0) entered forwarding state
[304322.244604] xenbr0: port 4(vif145.0) entered forwarding state
[304332.088501] xenbr0: port 4(vif145.0) entered disabled state
[304332.089510] xenbr0: port 4(vif145.0) entered disabled state
[304332.089659] device vif145.0 left promiscuous mode
[304332.089679] xenbr0: port 4(vif145.0) entered disabled state

I can't make much of that. :/

There's nothing of use in `/var/log/xen/xl-{vm name}`, either.

**Comment by talex5** [comment]
The tracing takes a bit of time at startup sharing the tracebuffer with dom0. Try commenting out this line in the generated `main.ml`:

    MProf_xen.share_with (module Gnt.Gntshr) (module OS.Xs) ~domid:0 trace_pages

If you can reproduce the bug after that, then it can be recorded. You'll just need to start an async thread to share the buffer after a couple of seconds instead of at startup.

If it's still too slow, there's another way to win the race: make the dom0 side slower. Can you e.g. put a sleep just before the point where the network device is added to the bridge? Maybe netback starts processing requests before that's set up? I don't know how the setup scripts work, but @MagnusS probably knows...

**Comment by yomimono** [comment]
It's looking like a regression in `mirage-net-xen` 1.3; @MagnusS ran into it when doing some other testing.

**Comment by yomimono** [comment]
Closing this out -- there's an open issue at https://github.com/mirage/mirage-net-xen/issues/20 .
