### ISSUE TITLE
The `Dhcp` functor is applied inside `Tcpip_stack_direct.Make`

### ISSUE THREAD

**Issue by Drup** [mirage/mirage-tcpip#168]
See https://github.com/mirage/mirage-tcpip/blob/2c820a1c211ec63b6e8b60087799a499ca22e16e/lib/tcpip_stack_direct.ml#L54

If we follow the logic, this should be an argument.

**Comment by Drup** [comment]
Actually, I went and look, and there is no `.mli` for the dhcp part, and it seems in general that this part didn't got a lot of love.

**Comment by avsm** [comment]
In general it would be good to make the Dhcp stack a client of the Tcpip stack. The plan is to use  https://github.com/haesbaert/hdhcp as the code base for this rather than the rather adhoc one thats currently in the mirage-tcpip codebase. (/cc @haesbaert)

**Comment by mor1** [comment]
There is also the code that Alistair (UROP student) has been working on. At
some point I believe he was in touch with Christiano but not sure where
that led. He seemed to have made some progress on producing a dhcpd at
least, and was (I believe) due to be talking with @yomimono about applying
some Irmin goodness to it. (I don't think he'd yet extracted it from
mirage-tcpip though.)

On 25 August 2015 at 13:30, Anil Madhavapeddy <notifications@github.com>
wrote:

> In general it would be good to make the Dhcp stack a client of the Tcpip
> stack. The plan is to use https://github.com/haesbaert/hdhcp as the code
> base for this rather than the rather adhoc one thats currently in the
> mirage-tcpip codebase. (/cc @haesbaert <https://github.com/haesbaert>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-tcpip/issues/168#issuecomment-134570460>
> .
>



-- 
Richard Mortier
mort@cantab.net

**Comment by haesbaert** [comment]
Not really, no one contacted me, wasn't aware there was another
implementation going on.

I have released the library needed for hdhcp on opam this weekend and hdhcp
seems to be functional, I've started to work on converting it to mirage.

**Comment by mor1** [comment]
@haesbaert Drat, sorry about that. My bad :( /cc @alistairfisher
Alistair has a Mirage DHCP server working, but based off the DHCP code that was here in mirage-tcpip so less complete than yours. After discussion with @yomimono, he's also started to work on applying Irmin to hold the state of the server. 

How far have you got with the Mirage server version so far -- perhaps worth the two of you joining forces?

**Comment by haesbaert** [comment]
I kinda just need to adapt the IO code functorizing the server, there isn't much code to write, the thing is I'm only now getting familiar with mirage, most of the work is just shuffling things here and there to fit. I hope to have it ready by next week or this weekend.
