### ISSUE TITLE
Support for NetBSD and Rumprun via bpf

### ISSUE THREAD

**Issue by mato** [mirage/mirage-tcpip#180]
As mentioned in mirage/mirage#479, the `direct` network stack needs support for NetBSD and thus Rumprun. This will also enable use of the direct stack on other BSDs which do not use `tap` devices or Linux-style `SOCK_RAW`.

In theory, this can be implemented using `bpf` to access the network, with a null packet filter.

**Comment by avsm** [comment]
Looks like the best place to put this is in the `NETIF` layer, which is in https://github.com/mirage/mirage-net-unix -- this stack implements `ETHIF` up
