### ISSUE TITLE
tests rely on other repositories which test fewer compiler versions

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-tcpip#185]
CI for `mirage-tcpip` tests that `mirage-www` and `mirage-skeleton` work with the commit under test.  Unfortunately `mirage-tcpip` tests with 4.01, but `mirage-www` itself doesn't, so commits can be made in `mirage-www` which aren't compatible with 4.01.  Those changes then make the tests for `mirage-tcpip` fail.

We should either drop support for 4.01 in `mirage-tcpip` (and generally in Mirage), or make sure that automated tests generally test the same compiler versions across commonly-required repositories.

**Comment by hannesm** [comment]
I'd be in favor to remove 4.01 support, there's also sexplib and cstruct syntax extension support via ppx only for >=4.02.

**Comment by yomimono** [comment]
This was resolved by #188.
