### ISSUE TITLE
restore branch history from pre 2012

### ISSUE THREAD

**Issue by avsm** [mirage/mirage-tcpip#270]
There's a bunch of valuable old bugfixes that got lost in the repo breakup of 2012. @balrajsingh has a branch here https://github.com/balrajsingh/mirage/tree/archive-pre-May2012/lib/net/direct

This will require a rebase though, so waiting until we are closer to freeze before doing the merge so outstanding PRs arent affected.

**Comment by mato** [comment]
If you intend to rebase `master` you may want to send a heads-up to the list about it, it'll break everyone's clones.

**Comment by avsm** [comment]
Yes indeed -- hence this PR to wait until we are closer to a release and there are fewer active PRs around. /cc @balrajsingh so he knows its not forgotten.

**Comment by balrajsingh** [comment]
I was wondering if this a good time to attempt the rebase.  Even if at some cost, maintaining correct OSS history is important - I'm sure we would all agree.

**Comment by yomimono** [comment]
Now's not terrible for that, although @djs55 may not agree - unfortunately I've introduced conflicts with his very reasonable MTU PR already, so it will need to be rebased regardless.

**Comment by balrajsingh** [comment]
any update?

**Comment by yomimono** [comment]
Now's a great time to do this.

**Comment by avsm** [comment]
This would mainly affect #243 which is conflicting anyway.  Now is indeed a good time to do this...

**Comment by samoht** [comment]
I am working on this now.

**Comment by samoht** [comment]
I have restored the full history here:

https://github.com/mirage/mirage-tcpip/tree/full-history

The only change is that I have added a parent to https://github.com/mirage/mirage-tcpip/commit/89427db07d9f89ae675cfeeec0d76bbd902d6427 to point to the merge point on mirage/mirage, using:

```
git filter-branch -f --parent-filter 'sed "s/^\$/-p dbea88cb64745dbbdff2b1d87f0f3171f4fdd9c5/"' master
```

Note that dbea88cb64745dbbdff2b1d87f0f3171f4fdd9c5 is a commit that I have added to revert d45b8c8779a42659206c44926ff8106bebb70a86.

Also note that that seems to have worked fine, as https://github.com/mirage/mirage-tcpip/blame/full-history/lib/tcp/state.ml shows commits from @balrajsingh before the fork.

@avsm @balrajsingh I am not sure if some patches got lost after the fork, but it would be worth reviewing https://github.com/mirage/mirage-tcpip/commit/89427db07d9f89ae675cfeeec0d76bbd902d6427 to check that it didn't reverted some useful things.

Once this is done, I'll send an email on the mirage list and we can force-push to `master`.

**Comment by avsm** [comment]
@balrajsingh any chance you could review https://github.com/mirage/mirage-tcpip/commit/89427db07d9f89ae675cfeeec0d76bbd902d6427 so that we can proceed with the branch switch?

**Comment by balrajsingh** [comment]
I looked at a few files and they did indeed have commits from before June 2012 so it should be fine.  Many thanks - @avsm it looks good to me to switch.

**Comment by avsm** [comment]
awesome, thanks for checking @balrajsingh.

@yomimono @samoht up to us to coordinate the branch switch then. Perhaps bring it up on the Mirage call on Wednesday to make sure there are no objections and then rebase outstanding PRs?

**Comment by yomimono** [comment]
A note to `mirageos-devel` with a proposed date and time would be good.  If there are no objections, I propose tomorrow at 15.00 UTC.  @hannesm's PR at #309 is fairly urgent but needs more attention before merging.

**Comment by avsm** [comment]
@samoht  I think we should go ahead and push this branch now -- I would like to topkg up tcpip next and this is blocking it.

**Comment by samoht** [comment]
Agreed. I'll rebase my branch and force-push then ...

**Comment by samoht** [comment]
Done!

**Comment by yomimono** [comment]
Hooray!  Thanks a lot, @samoht!

**Comment by samoht** [comment]
Note: the old master is now pointing at https://github.com/mirage/mirage-tcpip/tree/old-history We can delete that once everyone has rebased/don't care anymore.

**Comment by avsm** [comment]
@samoht: let's just keep the old branch around indefinitely. No cost and helps with long-running rebases if any exist that we are not aware of.
