### ISSUE TITLE
Mirage exhausts its memory while just answering ping requests (testing with ping -f)

### ISSUE THREAD

**Issue by vbmithr** [mirage/mirage-tcpip#33]
I'm running mirage-www under Xen with 64M of memory. When ping flooding, I don't loose packets but I have messages such that:

```
mm.c: Cannot handle page request order 1!
memalign(4096, 4096) failed.
```

repeating in a tight loop.

Looking at the code, it seems that Mirage tries to allocate memory to the point when it exhausts its memory, at that point, Gc.compact () is called and improve the situation, so that the unikernel never crashes with Out_of_memory.

Answering ping requests should not lead to allocate pages to the point it exhausts available memory, should it ?

**Comment by talex5** [comment]
[ sorry for the huge delay in replying! ]

OCaml (like many other GC'd languages) will keep allocating short-lived temporary values until it runs out of memory. Then it triggers the GC and starts again. This is normal and harmless.

What seems to be different here is that the GC is triggered by `Io_page`, which is very noisy about the problem. I suggest:

1. We should stop Mini-OS printing the scary `Cannot handle page request order 1!` message when malloc fails (although it can be a useful debugging aid if something else is silently ignoring the error).
2. Io_page should only print the `memalign(4096, 4096) failed` message if it tried to GC and there still wasn't enough space.

**Comment by talex5** [comment]
I've made a PR to remove the warning from io-page (https://github.com/mirage/io-page/pull/24) and I've applied a patch to Mini-OS to remove the warning there too.
