### ISSUE TITLE
Lwt_sequence is deprecated

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-tcpip#349]
A manual build (with `--dev`) fails with:
```
File "src/tcp/segment.ml", line 32, characters 8-31:
Error (warning 3): deprecated: module Lwt_sequence
 This module is an implementation detail of Lwt. See
   https://github.com/ocsigen/lwt/issues/361
```
Related to [ocsigen/lwt#361]

**Comment by dinosaure** [comment]
Any plan to fix it? I can take my time to try to fix it (needed to `git-mirage`).

**Comment by yomimono** [comment]
@dinosaure I won't have time to fix this in the next couple of weeks and would welcome a PR addressing it.

**Comment by dinosaure** [comment]
Ok. I will make something when @samoht will confirm to me that is the source of bug 👍 .

**Comment by bikallem** [comment]
@dinosaure may I know how you are planning to fix this issue. https://github.com/diml/lambda-term also needs to be updated to use a different doubly linked list. Will you be using a separate implementation of doubly linked list perhaps or per use Lwt_sequence with a different name?

**Comment by dinosaure** [comment]
According to what I said to @yomimono at the last hackathon, my goal is to provide a proved implementation of a double linked-list. I just discover in a [paper](https://hal.inria.fr/hal-00789533/document) than it's not possible to use Why3 in this case. So the plan is to use CFML/Coq instead. So, of course, this library will be outside `mirage-tcpip` and will be used in `lambda-term` too.

**Comment by yomimono** [comment]
See also https://github.com/mirage/mirage/issues/889 , the higher-level tracking issue for lwt 4.0.0 and mirage.

**Comment by hannesm** [comment]
since #388 this no longer uses lwt_sequence.
