### ISSUE TITLE
remove arpv4, and use hannesm/arp instead in mirageos unikernels

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-tcpip#386]
anyone wants to retain the arpv4 sublibrary? I'd be happy to transfer https://github.com/hannesm/arp to the mirage organisation and use this as default / only one in the mirage utility. my arp implementation isolates lwt in a smaller handler, and uses internally a map instead of a hashtable. see https://hannes.nqsb.io/Posts/ARP for reasoning behind it.

i use my own arp implementation in a dozen unikernels over one year now, it's pretty stable :) (and I don't see a reason to maintain two arp implementations). I'm happy to PR needed changes here and in mirage/mirage.

//cc @mirage/core

**Comment by mor1** [comment]
Also can't see a need to maintain two.

**Comment by avsm** [comment]
Yes, I'm fine with this once hannesm/arp#7 is merged (so that the tcpip duniverse is maintained)

**Comment by hannesm** [comment]
done now
