### ISSUE TITLE
Transient failures in the tests

### ISSUE THREAD

**Issue by kit-ty-kate** [mirage/mirage-tcpip#435]
The opam-repo-ci hit transient failures somewhere in tcpip's tests. See https://github.com/ocaml/opam-repository/pull/17663 for a bit more info.

No error logs were shown but the tests still exited with an erroneous exit status. Do the tests use the network or do something that could fail on a machine with high core count?

**Comment by MagnusS** [comment]
Does this happen with the latest release as well? We solved some test issues recently that could make tests fail depending on the order they were executed (fixes in  https://github.com/mirage/mirage-tcpip/pull/428)

**Comment by kit-ty-kate** [comment]
oh, that might be it. Sorry for the noise, I thought I was looking at version `5.0.1` but it was `4.0.0`, `4.1.0` and `5.0.0` only.

I'll disable the tests for those packages in opam-repository then. Thanks a lot!
