### ISSUE TITLE
Possible data corruption in User_buffer

### ISSUE THREAD

**Issue by ansiwen** [mirage/mirage-tcpip#486]
The `write` function in `User_buffer` possibly copies `Cstruct` values into a list and returns:

https://github.com/mirage/mirage-tcpip/blob/a7b799cb36435ecb810a92df05ff49fbd264bfbb/src/tcp/user_buffer.ml#L256-L277

which basically means it takes ownership, because copies of Cstruct share the data and it's not transparent when they will be flushed. This leads to problems, when code assumes otherwise and reuses the buffers after `write` returns, like the `Faraday` library. This leads to issues like this: https://github.com/anmonteiro/gluten/issues/29

I open this issue to clarify the contract conventions (if there are any) for the `write` function. Is the buffer ownership transferred, or only "borrowed" until `write` returns?

**Comment by haesbaert** [comment]
https://github.com/mirage/mirage-tcpip/blob/76033e871e0f0228b2417d9b1c1a93a9e8f51a74/src/tcp/user_buffer.ml#L256-L277

I'm not sure the authors considered this much, but as you can see only the very last case is not a clear offender.

**Comment by haesbaert** [comment]
Seems we missed this ?
https://github.com/mirage/mirage-flow/blob/e661203b4305b6ea34d625ec725337d854c4ae83/src/mirage_flow.mli#L78-L84

**Comment by ansiwen** [comment]
Ok, so ownership is transferred. Thanks. So I will close this.
