### ISSUE TITLE
`TLS.server_of_flow` seems don't working

### ISSUE THREAD

**Issue by Tim-ats-d** [mirage/mirage-tcpip#500]
Hi, I want to upgrade the TCP flow to a TLS flow with `TLS.server_of_flow` (https://docs.mirage.io/tls-mirage/Tls_mirage/Make/index.html#val-server_of_flow) [here](https://github.com/Psi-Prod/Mehari/blob/wip-merge/mehari/server_impl.ml#L43)
but when running the server, while the client successfully send a client hello the server shutdowns the connection with `FIN`.
I tested the certificates with `openssl s_server` and it works just fine.

I don't really know what to do to fix this issue, I tried to use the example of other library using this function. Does anyone have a fix/suggestion?

**Comment by hannesm** [comment]
I suspect without your code it is hard to debug. From my experience, the `server_of_flow` works fine, An example may be https://github.com/mirleft/nqsb.io/blob/master/unikernel.ml#L90 -- i.e. the `TLS.server_of_flow` is called on the flow which `TCP.listen` returned.

**Comment by hannesm** [comment]
Ah, sorry I missed the link to your code. Sorry, I'm not sure what e.g. `match%lwt` is doing.

**Comment by Tim-ats-d** [comment]
> An example may be https://github.com/mirleft/nqsb.io/blob/master/unikernel.ml#L90 -- i.e. the TLS.server_of_flow is called on the flow which TCP.listen returned.

Thanks for your answer :slightly_smiling_face:  . This is the way I do it.

 `match%lwt` is just a macro with a ppx to do `let* foo = ... in match foo with ...`, 
the same as `foo >>= function`

**Comment by Tim-ats-d** [comment]
eaculpa, I didn't create the issue on the right repo and the problem didn't come from this function.
