### ISSUE TITLE
Add a way to run tests without relying on xen

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-tcpip#68]
It would be great if we have a test suite for this component which could run without the need of Xen. That will greatly simplify the testing and even allow to have some Travis CI scripts to test pull requests.

**Comment by MagnusS** [comment]
It should now also be possible to use [mirage-vnetif](https://github.com/MagnusS/mirage-vnetif) for this.

**Comment by koleini** [comment]
Great! this test suite is to run tests against tcpip stack. We also need a test suite for netif itself. I suggest writing a tool stack to run tests against different layers, platforms and configurations based on user input (and Travis CI scripts), keep it in a repo like [here](https://github.com/mirage/mirage-perf).

**Comment by MagnusS** [comment]
Yes, mirage-vnetif is intended to be used to run automated tests on modules above netif on a single host. It can be used to write tests that can run without network access in Unix or Xen by replacing Netif with Vnetif in the Mirage network stack. There are some example unikernels [here](https://github.com/MagnusS/mirage-vnetif/tree/master/examples).

For writing scripted client/server tests you could also use [mirage-bench](https://github.com/MagnusS/mirage-bench), which is a test framework we developed for the Jitsu paper last year.

**Comment by samoht** [comment]
This is now fixed as we now have a very nice test framework, yay!

Writing more tests is still very welcome, though!
