### ISSUE TITLE
link error (undefined reference) in xen config

### ISSUE THREAD

**Issue by koleini** [mirage/mirage-tcpip#94]
errors arise when a library (packet here) uses checksum functions:

ld -d -static -nostdlib \
	  _build/main.native.o \
	  -L/home/.opam/4.01.0/lib/tcpip -ltcpip_xen_stubs \
	  $(pkg-config --static --libs mirage-xen) \
	  /usr/lib/gcc/x86_64-linux-gnu/4.8/libgcc.a \
	  -o mir-ofswitch.xen
_build/main.native.o: In function `camlChecksum__fun_1012':
(.text+0xa417a): undefined reference to `caml_ones_complement_checksum_list'
_build/main.native.o: In function `camlChecksum__fun_1014':
(.text+0xa41aa): undefined reference to `caml_ones_complement_checksum'
_build/main.native.o: In function `camlPacket__checksum_2668':
/home/.opam/4.01.0/build/packet.0.3.1/_build/lib/cstruct.ml:85: undefined reference to `caml_ones_complement_checksum_list'
_build/main.native.o: In function `camlPacket__marshal_3932':
/home/.opam/4.01.0/build/packet.0.3.1/_build/lib/cstruct.ml:85: undefined reference to `caml_ones_complement_checksum'
_build/main.native.o: In function `camlChecksum__2':
checksum.o:(.data+0x7f7c8): undefined reference to `caml_ones_complement_checksum_list'
checksum.o:(.data+0x7f7d0): undefined reference to `caml_ones_complement_checksum'

**Comment by mor1** [comment]
sorry, being slow. who do you mean by "developers of packet"? what is
"packet"?

On 30 December 2014 at 16:50, Masoud Koleini <notifications@github.com>
wrote:

> Right, modification is simple. Shall we inform developers of packet to
> apply the recent changes?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-tcpip/issues/94#issuecomment-68373181>.
>



-- 
Richard Mortier
mort@cantab.net

**Comment by koleini** [comment]
Packet library uses the same checksum code:

https://github.com/frenetic-lang/ocaml-packet

**Comment by talex5** [comment]
I think they should be able to use the public OCaml API (e.g. `Tcpip_checksum.ones_complement`) rather than calling C stubs directly.

Actually, it looks like they've duplicated the old C code in their source, but mirage (on Xen) doesn't use that. It was only working before because mirage-xen happened to provide a function with the same name and type...

**Comment by avsm** [comment]
I'm a bit confused -- which repo is "they" referring to here with the duplication?

**Comment by talex5** [comment]
@avsm: "they" = packet developers

https://github.com/frenetic-lang/ocaml-packet/blob/master/lib/checksum_stubs.c

**Comment by avsm** [comment]
Ah, Packet and not packet -- got it, thanks :)

**Comment by samoht** [comment]
should be reported to the `Packet` issue tracker I guess.
