### ISSUE TITLE
Allow the IP TTL to be set for UDP

### ISSUE THREAD

**Issue by infidel** [mirage/mirage-tcpip#95]
RFC 6762 (Multicast DNS) section 11 says:

```
   All Multicast DNS responses (including responses sent via unicast)
   SHOULD be sent with IP TTL set to 255.  This is recommended to
   provide backwards-compatibility with older Multicast DNS queriers
   (implementing a draft version of this document, posted in February
   2004) that check the IP TTL on reception to determine whether the
   packet originated on the local link.  These older queriers discard
   all packets with TTLs other than 255.
```

I guess this is a low priority but still worth noting. It could be done with an optional argument to Ipv4.allocate_frame (and Ipv6) and Udp.writev/write. I am not considering TCP here.

**Comment by haesbaert** [comment]
Are you considering implementing mdns by any chance ?

**Comment by infidel** [comment]
Cool. In case it's unclear, the latest code is in https://github.com/mirage/ocaml-dns (and fork)

**Comment by yomimono** [comment]
I believe we finally have this as of 03fa4eb957f9295d44e41db8b69ba08806d88022 .
